Enhance domain validation
eventespresso/eea-square-gateway pull request #21
Opened 2021-12-03 19:47 UTC by knazart

This resolves #18 

This adds auto domain registration when Digital Wallet get's enabled (and PM settings page is saved).

This also adds a "Register my site Domain" button on the settings page in case the domain was not verified with Apple in the time of auto registration mentioned above. This allows the user to trigger the domain registration manually.

Note: users that host this add-on on their own website [need to Verify](https://developer.squareup.com/docs/web-payments/apple-pay#step-1-register-your-sandbox-domain-with-apple) their domain name with Apple before they can register it in our App (PM settings page) and use Apple pay to checkout.

### Testing:
* [ ] Coming up...

2021-12-03 20:32 UTC, tn3rb commented on api/domains/DomainsApi.php
> + * handles Square Locations API calls
🤔

2021-12-03 20:33 UTC, tn3rb commented on api/domains/DomainsApi.php
> +    protected string $request_url;
noice 👌🏻

2021-12-03 20:35 UTC, tn3rb commented on api/domains/DomainsApi.php
> +            $request_error['error']['message'] = esc_html__(
where is `$request_error` coming from? does this need to be initialized?
my concern is that it would throw some error like "array key 'error' not found" if the array doesn't exist

2021-12-03 20:36 UTC, tn3rb commented on assets/css/eea-square-oauth.css
> +.eea-register-domain-btn {
:+

2021-12-03 20:36 UTC, tn3rb commented on assets/css/eea-square-oauth.css
> +    background-image: linear-gradient(#4a4d4f, #272a2b 85%, #1b1c1c);
oooo gettin' fancy ✨

2021-12-03 20:38 UTC, tn3rb commented on assets/js/eea-square-oauth.js
> +							console.log(response);
left in on purpose? (which is ok)

2021-12-03 20:45 UTC, tn3rb commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +        $pmFormParams = $this->addRegisterDomainButton($pmFormParams, $paymentMethod, $pmInstance);
much cleaner 👍🏻

2021-12-03 20:47 UTC, tn3rb commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +        }
beautiful and super easy to read 💯

2021-12-03 20:49 UTC, tn3rb approved these changes
### Absolutely Fantastic Job!!! 💯 x 🌮 

had a couple of comments regarding some super minor things but really awesome work and a great example of well written code IMHO!

2021-12-03 20:51 UTC, lorenzocaum commented
Hi Nazar, I activated the add domain validation branch with Event Espresso 4.10.19.p.

Then went to Event Espresso --> Payment Methods --> Square.

I see this add the top:

There was an error while doing the authorization health check: "This request could not be authorized.". Please re-authorize (Connect) for the Square payment method to function properly.

![‹ Lorenzo Caum Site — WordPress 2021-12-03 at 3 46 34 PM](https://user-images.githubusercontent.com/1079138/144670639-4b19a121-90b2-40ae-b1cc-3674f41453aa.jpg)

However, Square is already connected:

![‹ Lorenzo Caum Site — WordPress 2021-12-03 at 3 47 15 PM](https://user-images.githubusercontent.com/1079138/144670708-77b2dad1-eb8f-458b-8427-e9e312e4ecbb.jpg)

**Should I disconnect and then reconnect?**

I also noticed that the verified domain link points to the sandbox steps:

![‹ Lorenzo Caum Site — WordPress 2021-12-03 at 3 48 17 PM](https://user-images.githubusercontent.com/1079138/144670867-78b6ec43-5529-46aa-b240-f422353b3ade.jpg)

When it comes to getting started, I find that most customers want to go live. Should we point them here?

https://developer.squareup.com/docs/web-payments/apple-pay#production-configuration

Or do they need to add to Sandbox and then add to Production for this to work as expected?

2021-12-03 23:58 UTC, Pebblo requested changes

2021-12-03 23:58 UTC, Pebblo commented on api/domains/DomainsApi.php
> +    protected string $request_url;
Guys, I hate to sound like a broken record but typed properties are a PHP7.4 feature.

Afaik we are setting the min PHP version for this add-on to PHP7.1

2021-12-03 23:58 UTC, Pebblo commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +    protected array $squareData = [];
Please see my earlier comment.

Typed properties = PHP7.4

2021-12-03 23:58 UTC, Pebblo commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +    protected array $locations_list = [];
Please see my earlier comment.

Typed properties = PHP7.4

2021-12-13 22:30 UTC, Pebblo commented
/rebase

2021-12-14 11:50 UTC, Pebblo commented
@lorenzocaum 

> There was an error while doing the authorization health check: "This request could not be authorized.". Please re-authorize (Connect) for the Square payment method to function properly.

If you retest this now with the latest changes in this branch you show see a log entry (nor mor likely multiple entries) in Event Espresso -> Payment Methods -> Logs, what do they show?

Open the square payment method in a tab, then open the log list table in another, not the latest log entry ID number.

Refresh the Square payment method page, then refresh the log list table.

How many log entries do you get from that single refresh and post the contents of one here, please.

> When it comes to getting started, I find that most customers want to go live. Should we point them here?
> https://developer.squareup.com/docs/web-payments/apple-pay#production-configuration

Whilst I do agree with you, the sandbox link walks you through how to verify the domain more than the production version does. Sandbox steps you through what you need to do and then production basically just says 'add your domain to production' (which relies on everything you did in sandbox mode to work) so for now this needs to stay as is, or we write our own documentation for it.

2021-12-14 13:55 UTC, lorenzocaum commented
I updated to the newest version of the add domain validation branch.

Before disconnecting and reconnecting, I see 4 entries:

![‹ Lorenzo Caum Site — WordPress 2021-12-14 at 8 47 58 AM](https://user-images.githubusercontent.com/1079138/146010911-5ad86057-7025-44e3-970b-9de91a39b11d.jpg)

After switching back to the Square payment method tab and clicking disconnect, it showed this:

![‹ Lorenzo Caum Site — WordPress 2021-12-14 at 8 49 58 AM](https://user-images.githubusercontent.com/1079138/146010989-7be22ec9-4487-4b91-8ee3-b72b472a8a50.jpg)

I refreshed and the health check message at the top is gone. I then clicked to reconnect:

![‹ Lorenzo Caum Site — WordPress 2021-12-14 at 8 51 18 AM](https://user-images.githubusercontent.com/1079138/146011182-470fe2d3-e74b-4ad3-b08c-ac19d06e4554.jpg)

Next, I switched to the logs browser tab and refreshed it. It went from 4 entries to 7 entries:

![‹ Lorenzo Caum Site — WordPress 2021-12-14 at 8 52 44 AM](https://user-images.githubusercontent.com/1079138/146011424-5dabc348-745a-4e17-ae30-562e4a7f6744.jpg)

Here is the contents from number 8:

`Request access request response	{"webhook_action":"eea_square_grab_access_token","square_slug":"squareonsite","livemode":"1","client_id":"sq0idp-6fNz_8vadLmwPXVPCLzqlQ","expires_at":"2022-01-13T13:51:03Z","merchant_id":"S67C9S3R3829C","application_id":"sq0idp-6fNz_8vadLmwPXVPCLzqlQ"}`

2021-12-14 14:17 UTC, Pebblo commented
Ok, thanks, what is in #4, #5 and #7?

Or, click Download results at the bottom and attached that file here and I'll take a look.

2021-12-14 14:22 UTC, lorenzocaum commented
**4**

Square error	Refresh the token

**5**

OAuth error	{"error":{"code":"NO_ACCESS_TOKEN","message":"One or more authentication parameters are missing"}}

**7**

```
Exception thrown while revoking the access token, Square sent an error response: #0 /home/connect/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttpExceptionRequestException::create(Object(GuzzleHttpPsr7Request), Object(GuzzleHttpPsr7Response)) #1 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttpMiddleware::GuzzleHttp{closure}(Object(GuzzleHttpPsr7Response)) #2 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttpPromisePromise::callHandler(1, Object(GuzzleHttpPsr7Response), NULL) #3 /home/connect/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttpPromisePromise::GuzzleHttpPromise{closure}() #4 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttpPromiseTaskQueue->run(true) #5 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttpPromisePromise->invokeWaitFn() #6 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttpPromisePromise->waitIfPending() #7 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttpPromisePromise->invokeWaitList() #8 /home/connect/public_html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttpPromisePromise->waitIfPending() #9 /home/connect/public_html/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttpPromisePromise->wait() #10 /home/connect/public_html/src/Square/Controller.php(347): GuzzleHttpClient->request('POST', 'https://connect...', Array) #11 [internal function]: EventEspressoConnectSquareController->handleDeauthorize(Object(SymfonyComponentHttpFoundationRequest)) #12 /home/connect/public_html/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #13 /home/connect/public_html/vendor/symfony/http-kernel/HttpKernel.php(68): SymfonyComponentHttpKernelHttpKernel->handleRaw(Object(SymfonyComponentHttpFoundationRequest), 1) #14 /home/connect/public_html/vendor/silex/silex/src/Silex/Application.php(496): SymfonyComponentHttpKernelHttpKernel->handle(Object(SymfonyComponentHttpFoundationRequest), 1, true) #15 /home/connect/public_html/vendor/silex/silex/src/Silex/Application.php(477): SilexApplication->handle(Object(SymfonyComponentHttpFoundationRequest)) #16 /home/connect/public_html/web/index.php(10): SilexApplication->run() #17 {main}
```

**Download results**

Payment Logs for https://enzo12staging.wpengine.com
Query:
array ( 0 => array ( 'LOG_type' => 'gateway', 'LOG_time' => array ( 0 => 'BETWEEN', 1 => array ( 0 => EventEspresso\core\domain\entities\DbSafeDateTime::__set_state(array( '_datetime_string' => '', '_error_log_dir' => '', 'date' => '2021-06-14 04:00:00.000000', 'timezone_type' => 3, 'timezone' => 'UTC', )), 1 => EventEspresso\core\domain\entities\DbSafeDateTime::__set_state(array( '_datetime_string' => '', '_error_log_dir' => '', 'date' => '2021-12-15 04:59:59.000000', 'timezone_type' => 3, 'timezone' => 'UTC', )), ), ), ), 'order_by' => array ( 'LOG_time' => 'DESC', ), )
Results:
array ( 0 => array ( 'Log.LOG_ID' => '9', 'Log.LOG_time' => '2021-12-14 14:19:08', 'Log.OBJ_ID' => '10', 'Log.OBJ_type' => 'Payment_Method', 'Log.LOG_type' => 'gateway', 'Log.LOG_message' => 'a:1:{s:19:"Domain registration";s:21:"{"status":"VERIFIED"}";}', 'Log.LOG_wp_user' => '1', ), 1 => array ( 'Log.LOG_ID' => '8', 'Log.LOG_time' => '2021-12-14 13:51:06', 'Log.OBJ_ID' => '10', 'Log.OBJ_type' => 'Payment_Method', 'Log.LOG_type' => 'gateway', 'Log.LOG_message' => 'a:1:{s:31:"Request access request response";s:252:"{"webhook_action":"eea_square_grab_access_token","square_slug":"squareonsite","livemode":"1","client_id":"sq0idp-6fNz_8vadLmwPXVPCLzqlQ","expires_at":"2022-01-13T13:51:03Z","merchant_id":"S67C9S3R3829C","application_id":"sq0idp-6fNz_8vadLmwPXVPCLzqlQ"}";}', 'Log.LOG_wp_user' => '1', ), 2 => array ( 'Log.LOG_ID' => '6', 'Log.LOG_time' => '2021-12-14 13:48:40', 'Log.OBJ_ID' => '10', 'Log.OBJ_type' => 'Payment_Method', 'Log.LOG_type' => 'gateway', 'Log.LOG_message' => 'a:1:{s:19:"Request deauthorize";s:2937:"{"headers":{},"body":"{"error":"error_communicating_with_square","error_description":"Exception thrown while revoking the access token, Square sent an error response: #0 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/guzzle\\/src\\/Middleware.php(65): GuzzleHttp\\\\Exception\\\\RequestException::create(Object(GuzzleHttp\\\\Psr7\\\\Request), Object(GuzzleHttp\\\\Psr7\\\\Response))\\n#1 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(204): GuzzleHttp\\\\Middleware::GuzzleHttp\\\\{closure}(Object(GuzzleHttp\\\\Psr7\\\\Response))\\n#2 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(153): GuzzleHttp\\\\Promise\\\\Promise::callHandler(1, Object(GuzzleHttp\\\\Psr7\\\\Response), NULL)\\n#3 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/TaskQueue.php(48): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}()\\n#4 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(248): GuzzleHttp\\\\Promise\\\\TaskQueue-\\u003Erun(true)\\n#5 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(224): GuzzleHttp\\\\Promise\\\\Promise-\\u003EinvokeWaitFn()\\n#6 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(269): GuzzleHttp\\\\Promise\\\\Promise-\\u003EwaitIfPending()\\n#7 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(226): GuzzleHttp\\\\Promise\\\\Promise-\\u003EinvokeWaitList()\\n#8 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise-\\u003EwaitIfPending()\\n#9 \\/home\\/connect\\/public_html\\/vendor\\/guzzlehttp\\/guzzle\\/src\\/Client.php(182): GuzzleHttp\\\\Promise\\\\Promise-\\u003Ewait()\\n#10 \\/home\\/connect\\/public_html\\/src\\/Square\\/Controller.php(347): GuzzleHttp\\\\Client-\\u003Erequest(\\u0027POST\\u0027, \\u0027https:\\/\\/connect...\\u0027, Array)\\n#11 [internal function]: EventEspresso\\\\Connect\\\\Square\\\\Controller-\\u003EhandleDeauthorize(Object(Symfony\\\\Component\\\\HttpFoundation\\\\Request))\\n#12 \\/home\\/connect\\/public_html\\/vendor\\/symfony\\/http-kernel\\/HttpKernel.php(153): call_user_func_array(Array, Array)\\n#13 \\/home\\/connect\\/public_html\\/vendor\\/symfony\\/http-kernel\\/HttpKernel.php(68): Symfony\\\\Component\\\\HttpKernel\\\\HttpKernel-\\u003EhandleRaw(Object(Symfony\\\\Component\\\\HttpFoundation\\\\Request), 1)\\n#14 \\/home\\/connect\\/public_html\\/vendor\\/silex\\/silex\\/src\\/Silex\\/Application.php(496): Symfony\\\\Component\\\\HttpKernel\\\\HttpKernel-\\u003Ehandle(Object(Symfony\\\\Component\\\\HttpFoundation\\\\Request), 1, true)\\n#15 \\/home\\/connect\\/public_html\\/vendor\\/silex\\/silex\\/src\\/Silex\\/Application.php(477): Silex\\\\Application-\\u003Ehandle(Object(Symfony\\\\Component\\\\HttpFoundation\\\\Request))\\n#16 \\/home\\/connect\\/public_html\\/web\\/index.php(10): Silex\\\\Application-\\u003Erun()\\n#17 {main}"}","response":{"code":500,"message":"Internal Server Error"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}";}', 'Log.LOG_wp_user' => '1', ), 3 => array ( 'Log.LOG_ID' => '7', 'Log.LOG_time' => '2021-12-14 13:48:40', 'Log.OBJ_ID' => '10', 'Log.OBJ_type' => 'Payment_Method', 'Log.LOG_type' => 'gateway', 'Log.LOG_message' => 'a:1:{s:12:"Square error";s:2371:"Exception thrown while revoking the access token, Square sent an error response: #0 /home/connect/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttpExceptionRequestException::create(Object(GuzzleHttpPsr7Request), Object(GuzzleHttpPsr7Response)) #1 /home/connect/public_html/ven [...]

2021-12-14 14:29 UTC, Pebblo commented
Ok, thanks @lorenzocaum.

Your logs are basically showing that the Square data is already missing, which is to be expected I guess but not really helpful.

I'm going to roll with this update as it's better than what we have now but I think we need some changes with how Square is handling this data, I'll add some details in another ticket.

2021-12-14 14:29 UTC, merged