Enhance logging and don't try to verify the domain when the settings page is opened if the domain is already verified.
eventespresso/eea-square-gateway pull request #30
Opened 2022-03-02 18:04 UTC by Pebblo

Each time the square payment method setting page was loaded it tried to verify the domain even if it was already verified, so I've added a check to only do it automatically if the domain is not set to 'verified' already.

Also, when logging 'sensitive' data for the oAuth requests it would swap out the values to be just `***` but we need to know if the values are empty, or hidden so I've added a check for that so the log entry will now show `**empty**` or `**hidden**` (I need to know if keys are on the request so, can't just skip them when empty for example.

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.

2022-03-02 18:11 UTC, tn3rb approved these changes
technically everything looks great but I'll leave it to Nazar to comment on the business logic side of things since I have not dug into any of the Square documentation.

2022-03-02 20:01 UTC, knazart requested changes
I was baffled that this scenario wasn't covered as I for sure had it in my mind.

I'd rather recommend moving the `$this->registerBlogDomain($pmInstance);` into the conditional on [line 404](https://github.com/eventespresso/eea-square-gateway/blob/f6a172fd5e0f4ec2621c4307e55053c6ec3e08f5/payment_methods/SquareOnsite/forms/SettingsForm.php#L404) to have less duplicate code.

2022-03-02 20:19 UTC, Pebblo commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
Sure but I'm not sure how that would work within line 404.

Would you like to refactor this? I'd like to get this pushed live to go with the additional logging in master so I can see what is happening with these 'Square disconnecting' issues people are reporting.

2022-03-02 20:27 UTC, knazart commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
Yes, refactor.

2022-03-03 05:40 UTC, Pebblo commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
My apologies but I don't follow, am I merging this in or do you want to change it?

If this is being changed can you commit the changes as I'm not sure how the above would work around line 404, thanks.

2022-03-05 11:49 UTC, knazart commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
Yes, change it. Let me take a look.

2022-03-05 12:12 UTC, knazart commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
You know what ? Leave it. I took a look at the whole file and it looks good as is.

2022-03-05 12:13 UTC, knazart approved these changes

2022-03-07 12:26 UTC, Pebblo commented on payment_methods/SquareOnsite/forms/SettingsForm.php
> +            ){
Thanks bud :)

2022-03-07 12:27 UTC, merged